
language: node_js
node_js:
  - "12"

dist: xenial
services:
  - xvfb

addons:
  firefox: "49.0"

branches:
  only:
    - master

before_script:
  - npm install -g --silent @angular/cli@7.3.5
script:
  - npm run test
