language: node_js
node_js:
    - "node"
    - "14"
    - "12"
    - "11"

branches:
  only:
  - master


install:
  - npm install

before_script:
  - npm install -g @angular/cli

script:
    - npm test
