
language: node_js

node_js:
    - "node"
    - "12"

sudo: false

dist: xenial
services:
  - xvfb

addons:
  firefox: "49.0"

before_script:
    - npm install -g @angular/cli

cache:
  directories:
     - ./node_modules

script:
    - npm test --watch=false --no-progress --single-run
